name: Lucky Router CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - latest
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crystal_version:
          - 1.6.2
          - latest
        experimental:
          - false
        include:
          - os: windows-latest
            crystal_version: latest
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
